# App name
spring.application.name=telegram-av-bot

# ========================
# DATABASE (PostgreSQL)
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/securty_bot
spring.datasource.username=postgres
spring.datasource.password=root123

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (agar ishlatsang)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========================
# TELEGRAM BOT
# ========================
bot.token=8761323906:AAHQMh2Xb6IIPvPpEsQ_Hh8cAIuqQmXiDqQ
bot.username=secure_scan_bot

# ========================
# Tashqi Api sozlamalari
api.urlhaus.url=https://urlhaus-api.abuse.ch/v1/url/